Repository the-1Riddle/Leetcode-Solutions, pull requests merged in 2024-05, with the labels that each got.

#5 Create find-the-maximum-sum-of-node-values.cs
  C#/find-the-maximum-sum-of-node-values.cs
Labels: documentation, enhancement, good first issue, question

#6 Update managers-with-at-least-5-direct-reports.sql
  MySQL/managers-with-at-least-5-direct-reports.sql
Labels: documentation, enhancement

#9 2597. The Number of Beautiful Subsets
  C#/the-number-of-beautiful-subsets.cs
Labels: enhancement, 💡 feature
